version: '3'

services:
  php_crud:
    build: .
    container_name: php_crud
    image: latest
    volumes:
      - ./src:/var/www/html
      - ./httpd.vhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 81:80